version: '3.9'

services:
  climbing-stairs:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge
