version: 2.1

jobs:
  build:
    docker:
      - image: docker:26.1.0

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Build and test Docker image
          command: |
            docker build -t hollowsam/climbing_stairs:latest --target builder .
            docker build -t hollowsam/climbing_stairs:deploy --target deploy .

  deploy:
    docker:
      - image: docker:26.1.0  # Use a lightweight image for deployment tasks

    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u hollowsam -p stdin  # Securely use environment variable

      - run:
          name: Push deployment image
          command: |
            docker push hollowsam/climbing_stairs:latest

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Run deployment only after successful build
