version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:22.04

    working_directory: /app

    steps:
      - checkout

      # Install dependencies (new step)
      - run:
          name: Install Dependencies
          command: |
            apt-get update  # Update package lists (Ubuntu/Debian)
            apt-get install -y curl  # Install curl

      # Install Docker Engine (updated command)
      - run:
          name: Install Docker Engine
          command: |
            sh -c "$(curl -fsSL https://get.docker.com/)"

      - run:
          name: Build and test Docker image
          command: |
            docker build -t climbing_stairs:latest .
            # docker build -t climbing_stairs:deploy --target deploy .

  deploy:
    docker:
      - image: docker:26.1.0  # Use a lightweight image for deployment tasks

    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u hollowsam -p stdin  # Securely use environment variable
            docker tag climbing_stairs:latest hollowsam/climbing_stairs:latest 

      - run:
          name: Push deployment image
          command: |
            docker push hollowsam/climbing_stairs:latest

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Run deployment only after successful build
