version: 2.1

jobs:
  build:
    docker:
      - image: docker:26.1.0

    working_directory: /app

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t climbing-stairs .

      - run:
          name: Run Docker container
          command: |
            docker run climbing-stairs
