version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout
      - setup_remote_docker:
          version: stable
      - run:
          name: Build Docker Image
          command: |
            docker build -t climbing_stairs:latest .
      - run:
          name: Push Docker Image to Docker Hub (Optional Username)
          command: |
            if [[ -n "$DOCKER_USERNAME" ]]; then
              echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker tag climbing_stairs:latest "$DOCKER_USERNAME/climbing_stairs:latest"
            fi
            docker push climbing_stairs:latest

workflows:
  build_test_deploy:
    jobs:
      - build
