version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t climbing-stairs .

      - run:
          name: Run Docker container
          command: |
            docker run climbing-stairs
