name: CI/CD Climbing Stairs Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: samirsth09/devops-intern-task@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.SAM_GPT }}
          OPENAI_API_MODEL: "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas

      - name: Build Docker image
        run: docker build -t climbing-stairs .

      - name: Run Docker container
        run: docker run climbing-stairs


