name: CI/CD Climbing Stairs Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AI Code Reviewer (secure)
        uses: samirsth09/devops-intern-task@main
        with:
          args: |
            github-token ${{ secrets.GITHUB_TOKEN }}
            --openai-api-key ${{ secrets.SAM_GPT }}
            --openai-api-model gpt-4
            --exclude "**/*.json, **/*.md"

      - name: Build Docker image
        run: docker build -t climbing-stairs .

      - name: Run Docker container
        run: docker run climbing-stairs
